before:
  hooks:
    - go mod tidy
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    main: ./
    binary: tfautomv
archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
    format_overrides:
      - goos: windows
        format: zip
    files:
      - README.md
      - LICENSE
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: '{{ .Tag }}-next'
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
brews:
- name: tfautomv
  homepage: https://github.com/padok-team/tfautomv
  tap:
    owner: padok-team
    name: tfautomv
nfpms:
  - maintainer: Arthur Busser <arthurb@padok.fr>
    description: Tf Automove
    homepage: https://github.com/padok-team/tfautomv
    license: Apache 2.0
    file_name_template: '{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}'
    formats:
      - deb