before:
  hooks:
    - go mod tidy
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    main: ./
    binary: tfautomv
archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
    format_overrides:
      - goos: windows
        format: zip
checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
release:
  prerelease: auto
brews:
  - name: tfautomv
    homepage: https://github.com/busser/tfautomv
    description: Generate Terraform moved blocks automatically for painless refactoring
    license: Apache-2.0
    tap:
      owner: busser
      name: homebrew-tap
    install: |
      bin.install "tfautomv"
    test: |
      system "#{bin}/tfautomv -version"
aurs:
  - name: tfautomv-bin
    homepage: https://github.com/busser/tfautomv
    description: Generate Terraform moved blocks automatically for painless refactoring
    maintainers:
      - Arthur Busser <arthur dot busser at gmail dot com>
    private_key: "{{ .Env.AUR_KEY }}"
    license: Apache-2.0
    git_url: "ssh://aur@aur.archlinux.org/tfautomv-bin.git"
    skip_upload: auto
    provides:
      - tfautomv
    optdepends:
      - "terraform: for running Terraform"
    package: |-
      install -Dm755 "./tfautomv" "$pkgdir/usr/bin/tfautomv"
      install -Dm644 "./LICENSE" "$pkgdir/usr/share/licenses/tfautomv/LICENSE"
